spring:
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 12345
    username: root
    url: jdbc:mysql://localhost:3306/like_book?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC

